name: israel_tcc
recipe: drupal10
config:
  webroot: .
  php: '8.1'
  framework: drupal10
  site: israel_tcc
  id: f263d325-408a-4f30-92be-1e3903ae5baf
  xdebug: true
  index: false
  cache: false
  edge: false
services:
  appserver:
    xdebug: true
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        XDEBUG_SESSION_START: lando
        DRUSH_OPTIONS_URI: "https://israel_tcc.lndo.site"
    config:
      php: .lando/config/php.ini
  node:
    type: 'node:10'
    globals:
      gulp-cli: latest
  database:
    type: 'mariadb:10.4'
tooling:
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node
  bower:
    service: node
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml --colors
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml --colors
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-pehp-ext-xdebug.ini && docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm && echo "Xdebug enabled"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm && echo "Xdebug disabled"
    user: root
